version: '3'
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: java-demo
      POSTGRES_USER: java-db-user
      POSTGRES_PASSWORD: db1234
  app:
    build: .
    ports:
      - "9000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/java-demo
      SPRING_DATASOURCE_USERNAME: java-db-user
      SPRING_DATASOURCE_PASSWORD: db1234
    depends_on:
      - db
volumes:
  postgres-data:
