FROM maven:3.6.3-openjdk-14 AS MAVEN_BUILD
WORKDIR /build
COPY . /build
RUN mvn clean package -DskipTests

FROM openjdk:14-alpine
COPY --from=MAVEN_BUILD /build/target/JavaProject-0.0.1-SNAPSHOT.jar /demo.jar
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ENTRYPOINT ["java","-jar","demo.jar"]
